language: node_js

node_js:
  - '7'

# fail asap when there is a failure
matrix:
  fast_finish: true

# cache node modules
cache:
  yarn: true

before_install:
  # Install Watchman dependency
  - git clone --depth=1 --branch=v4.7.0 https://github.com/facebook/watchman.git
  - pushd watchman && ./autogen.sh && ./configure --without-python && make && sudo make install && popd

install: yarn

after_success: yarn run coverage
