language: node_js

node_js:
  - '7'

# fail asap when there is a failure
matrix:
  fast_finish: true

# cache node modules
cache:
  directories:
    # Yarn
    - $HOME/.yarn-cache

env:
  global:
  - DEBUG: phenomic:*

before_install:
  # Install Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  # Install Watchman dependency
  - git clone --depth=1 --branch=v4.7.0 https://github.com/facebook/watchman.git
  - pushd watchman && ./autogen.sh && ./configure --without-python && make && sudo make install && popd

install: yarn

after_success: yarn run coverage

# for Yarn, to build some native deps
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
