# http://www.appveyor.com/docs/appveyor-yml
environment:
  matrix:
    - nodejs_version: '8'

  DEBUG: phenomic:*

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - yarn --version
  - yarn

test_script:
  - yarn test-without-lint
  - yarn posttest

cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules -> package.json
  - website/.screenshots -> website/content/showcase/entry
  - website/public/showcase/entry -> website/content/showcase/entry

version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true

init:
  # debugging Appveyor build. More info:
  # https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
